development: &non_production_settings
  jshub_version: 0.4
      
test:
  <<: *non_production_settings

production:
  <<: *non_production_settings

passenger:
  <<: *non_production_settings

gromit:
  <<: *non_production_settings
  
jshub:
  <<: *non_production_settings